// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {appserver} from '../models';

export function Account():Promise<Record<string, any>>;

export function GenerateStoryboard():Promise<appserver.Turn>;

export function InterruptTurn(arg1:string,arg2:string):Promise<void>;

export function ResolveApproval(arg1:string,arg2:string):Promise<void>;

export function Start():Promise<void>;

export function StartChatGPTLogin():Promise<Record<string, any>>;

export function StartTurn(arg1:string):Promise<appserver.Turn>;
