// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Account() {
  return window['go']['appapi']['AgentAPI']['Account']();
}

export function InterruptTurn(arg1, arg2) {
  return window['go']['appapi']['AgentAPI']['InterruptTurn'](arg1, arg2);
}

export function ResolveApproval(arg1, arg2) {
  return window['go']['appapi']['AgentAPI']['ResolveApproval'](arg1, arg2);
}

export function Start() {
  return window['go']['appapi']['AgentAPI']['Start']();
}

export function StartChatGPTLogin() {
  return window['go']['appapi']['AgentAPI']['StartChatGPTLogin']();
}

export function StartTurn(arg1) {
  return window['go']['appapi']['AgentAPI']['StartTurn'](arg1);
}
