// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRun(arg1) {
  return window['go']['appapi']['AssetAPI']['CancelRun'](arg1);
}

export function DataURL(arg1) {
  return window['go']['appapi']['AssetAPI']['DataURL'](arg1);
}

export function GenerateImage(arg1, arg2) {
  return window['go']['appapi']['AssetAPI']['GenerateImage'](arg1, arg2);
}

export function GenerateVideo(arg1, arg2) {
  return window['go']['appapi']['AssetAPI']['GenerateVideo'](arg1, arg2);
}

export function GetRun(arg1) {
  return window['go']['appapi']['AssetAPI']['GetRun'](arg1);
}

export function Import(arg1, arg2, arg3) {
  return window['go']['appapi']['AssetAPI']['Import'](arg1, arg2, arg3);
}

export function ImportExternalVideo(arg1) {
  return window['go']['appapi']['AssetAPI']['ImportExternalVideo'](arg1);
}

export function ImportReference(arg1) {
  return window['go']['appapi']['AssetAPI']['ImportReference'](arg1);
}

export function PendingApprovals() {
  return window['go']['appapi']['AssetAPI']['PendingApprovals']();
}

export function ResolveApproval(arg1, arg2) {
  return window['go']['appapi']['AssetAPI']['ResolveApproval'](arg1, arg2);
}

export function SelectVersion(arg1, arg2) {
  return window['go']['appapi']['AssetAPI']['SelectVersion'](arg1, arg2);
}
