// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {media} from '../models';
import {provider} from '../models';
import {domain} from '../models';
import {approval} from '../models';

export function CancelRun(arg1:string):Promise<media.Result>;

export function Capabilities():Promise<provider.Capabilities>;

export function DataURL(arg1:string):Promise<string>;

export function GenerateImage(arg1:string,arg2:provider.ImageRequest):Promise<media.Result>;

export function GenerateVideo(arg1:string,arg2:provider.VideoRequest):Promise<media.Result>;

export function GetRun(arg1:string):Promise<media.Result>;

export function Import(arg1:string,arg2:string,arg3:domain.AssetKind):Promise<domain.Asset>;

export function ImportExternalVideo(arg1:string):Promise<domain.Asset>;

export function ImportReference(arg1:string):Promise<domain.Asset>;

export function PendingApprovals():Promise<Array<approval.Request>>;

export function ResolveApproval(arg1:string,arg2:boolean):Promise<approval.Decision>;

export function SelectVersion(arg1:string,arg2:string):Promise<domain.Shot>;
