// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {exporter} from '../models';

export function ApplyStoryboard(arg1:Array<domain.Scene>,arg2:Array<domain.Shot>,arg3:boolean):Promise<domain.Snapshot>;

export function Create(arg1:string,arg2:string):Promise<domain.Snapshot>;

export function Current():Promise<domain.Snapshot>;

export function Export():Promise<exporter.Result>;

export function Open(arg1:string):Promise<domain.Snapshot>;

export function RebuildIndex():Promise<void>;

export function SaveScene(arg1:domain.Scene):Promise<domain.Snapshot>;

export function SaveShot(arg1:domain.Shot):Promise<domain.Snapshot>;
