// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyStoryboard(arg1, arg2, arg3) {
  return window['go']['appapi']['ProjectAPI']['ApplyStoryboard'](arg1, arg2, arg3);
}

export function Create(arg1, arg2) {
  return window['go']['appapi']['ProjectAPI']['Create'](arg1, arg2);
}

export function Current() {
  return window['go']['appapi']['ProjectAPI']['Current']();
}

export function Export() {
  return window['go']['appapi']['ProjectAPI']['Export']();
}

export function Open(arg1) {
  return window['go']['appapi']['ProjectAPI']['Open'](arg1);
}

export function RebuildIndex() {
  return window['go']['appapi']['ProjectAPI']['RebuildIndex']();
}

export function SaveScene(arg1) {
  return window['go']['appapi']['ProjectAPI']['SaveScene'](arg1);
}

export function SaveShot(arg1) {
  return window['go']['appapi']['ProjectAPI']['SaveShot'](arg1);
}
