// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project} from '../models';
import {domain} from '../models';
import {exporter} from '../models';

export function ChooseDirectory(arg1:string):Promise<string>;

export function Create(arg1:string,arg2:project.CreateOptions):Promise<domain.Snapshot>;

export function Current():Promise<domain.Snapshot>;

export function Export():Promise<exporter.Result>;

export function Open(arg1:string):Promise<domain.Snapshot>;

export function RebuildIndex():Promise<void>;

export function SaveSettings(arg1:domain.Project):Promise<domain.Snapshot>;
