// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDirectory(arg1) {
  return window['go']['appapi']['ProjectAPI']['ChooseDirectory'](arg1);
}

export function Create(arg1, arg2) {
  return window['go']['appapi']['ProjectAPI']['Create'](arg1, arg2);
}

export function Current() {
  return window['go']['appapi']['ProjectAPI']['Current']();
}

export function Export() {
  return window['go']['appapi']['ProjectAPI']['Export']();
}

export function Open(arg1) {
  return window['go']['appapi']['ProjectAPI']['Open'](arg1);
}

export function RebuildIndex() {
  return window['go']['appapi']['ProjectAPI']['RebuildIndex']();
}

export function SaveSettings(arg1) {
  return window['go']['appapi']['ProjectAPI']['SaveSettings'](arg1);
}
