// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildTimeline(arg1) {
  return window['go']['appapi']['RenderAPI']['BuildTimeline'](arg1);
}

export function Cancel(arg1) {
  return window['go']['appapi']['RenderAPI']['Cancel'](arg1);
}

export function Locate(arg1) {
  return window['go']['appapi']['RenderAPI']['Locate'](arg1);
}

export function ProbeAsset(arg1) {
  return window['go']['appapi']['RenderAPI']['ProbeAsset'](arg1);
}

export function Runtime() {
  return window['go']['appapi']['RenderAPI']['Runtime']();
}

export function Start(arg1) {
  return window['go']['appapi']['RenderAPI']['Start'](arg1);
}

export function Validate(arg1) {
  return window['go']['appapi']['RenderAPI']['Validate'](arg1);
}
