// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {render} from '../models';
import {appapi} from '../models';

export function BuildTimeline(arg1:string):Promise<domain.EpisodeEdit>;

export function Cancel(arg1:string):Promise<void>;

export function Locate(arg1:string):Promise<string>;

export function ProbeAsset(arg1:string):Promise<domain.MediaInfo>;

export function Runtime():Promise<render.RuntimeStatus>;

export function Start(arg1:string):Promise<domain.Run>;

export function Validate(arg1:string):Promise<appapi.TimelineValidation>;
