// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {runtime} from '../models';

export function DetectCodex():Promise<runtime.Status>;

export function EnsureCodex():Promise<runtime.Status>;
