// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DetectCodex() {
  return window['go']['appapi']['RuntimeAPI']['DetectCodex']();
}

export function EnsureCodex() {
  return window['go']['appapi']['RuntimeAPI']['EnsureCodex']();
}
