// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {provider} from '../models';
import {appapi} from '../models';

export function DeleteOpenAIKey():Promise<void>;

export function ProbeCapabilities():Promise<provider.Capabilities>;

export function SetOpenAIKey(arg1:string):Promise<void>;

export function Status():Promise<appapi.SettingsStatus>;
