// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteOpenAIKey() {
  return window['go']['appapi']['SettingsAPI']['DeleteOpenAIKey']();
}

export function ProbeCapabilities() {
  return window['go']['appapi']['SettingsAPI']['ProbeCapabilities']();
}

export function SetOpenAIKey(arg1) {
  return window['go']['appapi']['SettingsAPI']['SetOpenAIKey'](arg1);
}

export function Status() {
  return window['go']['appapi']['SettingsAPI']['Status']();
}
