// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {appapi} from '../models';

export function CreateEpisode(arg1:string):Promise<domain.Snapshot>;

export function ExportFountain(arg1:string):Promise<appapi.FountainResult>;

export function ImportFountain(arg1:string):Promise<domain.Snapshot>;

export function SaveCharacter(arg1:domain.Character):Promise<domain.Snapshot>;

export function SaveEdit(arg1:domain.EpisodeEdit):Promise<domain.Snapshot>;

export function SaveEpisode(arg1:domain.Episode):Promise<domain.Snapshot>;

export function SaveLocation(arg1:domain.Location):Promise<domain.Snapshot>;

export function SaveProp(arg1:domain.Prop):Promise<domain.Snapshot>;

export function SaveScene(arg1:domain.Scene):Promise<domain.Snapshot>;

export function SaveShot(arg1:domain.Shot):Promise<domain.Snapshot>;
