// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEpisode(arg1) {
  return window['go']['appapi']['StoryAPI']['CreateEpisode'](arg1);
}

export function ExportFountain(arg1) {
  return window['go']['appapi']['StoryAPI']['ExportFountain'](arg1);
}

export function ImportFountain(arg1) {
  return window['go']['appapi']['StoryAPI']['ImportFountain'](arg1);
}

export function SaveCharacter(arg1) {
  return window['go']['appapi']['StoryAPI']['SaveCharacter'](arg1);
}

export function SaveEdit(arg1) {
  return window['go']['appapi']['StoryAPI']['SaveEdit'](arg1);
}

export function SaveEpisode(arg1) {
  return window['go']['appapi']['StoryAPI']['SaveEpisode'](arg1);
}

export function SaveLocation(arg1) {
  return window['go']['appapi']['StoryAPI']['SaveLocation'](arg1);
}

export function SaveProp(arg1) {
  return window['go']['appapi']['StoryAPI']['SaveProp'](arg1);
}

export function SaveScene(arg1) {
  return window['go']['appapi']['StoryAPI']['SaveScene'](arg1);
}

export function SaveShot(arg1) {
  return window['go']['appapi']['StoryAPI']['SaveShot'](arg1);
}
